--------------------------------------------------------
--  Fichier créé - jeudi-avril-30-2020   
--------------------------------------------------------
REM INSERTING into BS708164LM20.CARSRACINGSTABLE
SET DEFINE OFF;
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('1','MERCEDES-AMG F1 W10','AVAILABLE','1');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('2','MERCEDES-AMG F1 W10','AVAILABLE','1');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('3','FERRARI SF90','AVAILABLE','2');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('4','FERRARI SF90','AVAILABLE','2');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('5','RED BULL RB15','AVAILABLE','3');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('6','RED BULL RB15','AVAILABLE','3');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('7','RENAULT R.S.19','AVAILABLE','5');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('8','RENAULT R.S.19','AVAILABLE','5');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('9','MCLAREN MCL34','AVAILABLE','4');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('10','MCLAREN MCL34','AVAILABLE','4');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('11','TORO ROSSO STR14','AVAILABLE','6');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('12','TORO ROSSO STR14','AVAILABLE','6');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('13','RACING POINT RP19','AVAILABLE','7');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('14','RACING POINT RP19','AVAILABLE','7');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('15','ALFA ROMEO C38','AVAILABLE','8');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('16','ALFA ROMEO C38','AVAILABLE','8');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('17','HAAS VF-19','AVAILABLE','9');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('18','HAAS VF-19','AVAILABLE','9');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('19','WILLIAMS FW42','AVAILABLE','10');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('20','WILLIAMS FW42','AVAILABLE','10');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('21','MIAGE TURBO BOOST','AVAILABLE','11');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('22','MIAGE TURBO BOOST','CRASHED','11');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('23','MARAIS QUATRELLE','MAINTENANCE','12');
Insert into BS708164LM20.CARSRACINGSTABLE (IDCAR,NAME,STATE,IDRACINGSTABLE) values ('24','MARAIS QUATRELLE','CRASHED','12');
