--------------------------------------------------------
--  Fichier créé - jeudi-avril-30-2020   
--------------------------------------------------------
REM INSERTING into BS708164LM20.CARRACINGSTABLEPILOTE
SET DEFINE OFF;
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('1','1','1');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('2','2','2');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('3','3','5');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('4','4','6');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('5','5','4');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('6','6','3');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('7','7','11');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('8','8','12');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('9','9','8');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('10','10','7');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('11','11','9');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('12','12','10');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('13','13','13');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('14','14','14');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('15','15','16');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('16','16','15');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('17','17','17');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('18','18','18');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('19','19','19');
Insert into BS708164LM20.CARRACINGSTABLEPILOTE (IDCARRACINGSTABLEPILOTE,IDCAR,IDRACINGSTABLEPILOTE) values ('20','20','20');
